name: Terragrunt states

on:
  push:
    branches:
      - main
    paths:
      - states/**

  pull_request:
    branches:
      - main
    paths:
      - states/**

  workflow_dispatch:
    inputs:
      dir_to_apply:
        description: >
          The directory of the resource grouping to apply,
          for example, to apply changes in "main/us-west-2/development/app" directory resource grouping,
          value should be "main/us-west-2/development/app".
          To minimize blast radius, this only supports one resource grouping at a time.
        required: true
        default: 'main/us-west-2/development/app'
      terragrunt_action:
        description: >
          The action for Terragrunt to run, options are "apply", "plan". Defaults to "plan", if not specified.
        required: true
        default: 'apply'
jobs:
  get-changed-states:
    name: Get modified states
    outputs:
      matrix: ${{ steps.filter.outputs.matrix }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v14.1
        with:
          files: states/**

      - id: filter
        name: Filter
        run: |
          export states="{}"
          export items="[]"
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]
            then
              states='{"states": ["states/'${{ github.event.inputs.dir_to_apply }}'"]}'
          else
            for dir in `echo ${{ steps.changed-files.outputs.all_changed_and_modified_files }} | tr ' ' '\n' | grep '(*.hcl$\|.yaml$\|.yml$)' | xargs -I {} dirname {} | sort | uniq`
            do
              if [[ -f $dir/terragrunt.hcl ]] && [[ "$dir" != "states" ]]
                then
                  items=$(echo $items | jq -c --arg obj $dir '. += [$obj]')
              fi
            done
            states=$(echo {} | jq -c -s --argjson obj $items '{states: $obj}')
          fi
          echo "::set-output name=matrix::$(echo "${states}")"

  terragrunt:
    name: "Terragrunt"
    runs-on: ubuntu-latest
    if: "${{ needs.get-changed-states.outputs.states != '{\"states\": []}' }}"
    needs: get-changed-states
    strategy:
      matrix: ${{ fromJson(needs.get-changed-states.outputs.matrix) }}
    defaults:
      run:
        working-directory: ${{ matrix.states }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.IAC_PAT }}

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.1
        with:
          terragrunt_version: 0.36.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terragrunt Init
        id: init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terragrunt init

      - name: Terragrunt fmt
        id: terragrunt_fmt
        run: terragrunt fmt -check
        continue-on-error: true

      - name: Terragrunt Apply
        id: tg_apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        if: ${{ github.event_name == 'push' || github.event.inputs.terragrunt_action == 'apply' }}
        run: terragrunt apply -auto-approve -input=false --terragrunt-source-update

      - name: Get generated local files
        id: generated_files
        if: steps.tg_apply.outcome == 'success'
        run: |
          set -x
          cd $(dirname $(find .terragrunt-cache -name terragrunt.hcl))
          generated_files=$(jq -r '.resources[] | select(.type=="local_file") | .instances[].attributes.filename' terraform.tfstate)
          echo $generated_files
          echo "::set-output name=generated_files::$generated_files"

      - name: Add local files back to repository
        if: steps.generated_files.outputs.generated_files != ''
        run: |
          cd $(dirname $(find .terragrunt-cache -name terragrunt.hcl))
          prefix=$(pwd | grep -oP 'states/\K([^.]*)')
          for file in ${{ steps.generated_files.outputs.generated_files }}
            do
              mkdir -p ${{ github.workspace }}/generated/$prefix/$(dirname $file)
              cp -r $file ${{ github.workspace }}/generated/$prefix/$(dirname $file)/
          done

      - name: Commit local files back to repository
        if: steps.generated_files.outputs.generated_files != ''
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Applying generated files back to repository
          file_pattern: "generated/**"
          push_options: --force

      - name: Terragrunt Plan
        id: tg_plan
        if: ${{ github.event_name == 'pull_request' || github.event.inputs.terragrunt_action == 'plan' }}
        run: |
          terragrunt plan -no-color -input=false --terragrunt-source-update > report.txt || status=$?
          REPORT=$(cat report.txt)
          REPORT="${REPORT//'%'/'%25'}"
          REPORT="${REPORT//$'\n'/'%0A'}"
          REPORT="${REPORT//$'\r'/'%0D'}"
          echo "::set-output name=report::$REPORT"
          exit $status
        continue-on-error: true

      - name: Setup Infracost
        if: ${{ github.event_name == 'pull_request' }}
        uses: infracost/actions/setup@v1
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Generate Infracost comment
        if: ${{ github.event_name == 'pull_request' }}
        id: cost_comment
        run: |
          infracost breakdown --path . --format json --out-file infracost.json
          REPORT=$(infracost output --path infracost.json --format github-comment --show-skipped)
          REPORT=$(cat report.txt)
          REPORT="${REPORT//'%'/'%25'}"
          REPORT="${REPORT//$'\n'/'%0A'}"
          REPORT="${REPORT//$'\r'/'%0D'}"
          echo "::set-output name=report::$REPORT"

      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        if: ${{ github.event_name == 'pull_request' }}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: "Report for state ${{ matrix.states }}:"

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v1
        if: ${{ github.event_name == 'pull_request' }}
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### Report for state ${{ matrix.states }}:
            #### Format and Style 🖌 `${{ steps.fmt.outcome }}`
            #### Plan 📖 `${{ steps.tg_plan.outcome }}`
            <details><summary>Show plan details</summary>

            ```
            ${{ steps.tg_plan.outputs.report }}
            ```
            </details>
            ${{ steps.cost_comment.outputs.report }}
          edit-mode: replace

      - name: Status
        if: ${{ github.event_name == 'pull_request' && steps.tg_plan.outcome == 'failure' }}
        run: exit 1
